<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-L754054H" failures="1" tests="1" name="TestRunner.failedTestRunner" time="59.146" errors="0" timestamp="2022-10-06T01:15:01 IST" skipped="0">
  <testcase classname="TestRunner.failedTestRunner" name="runScenario" time="59.146">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at StepDefinition.stepDefinition.user_should_found_in_the_table(stepDefinition.java:219)
at âœ½.User should found in the table(file:///C:/Users/mayan/eclipse-workspace/CucumberFramworkProject/src/test/java/Features/userListPage.feature:17)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- TestRunner.failedTestRunner -->
